sudo: required

language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    - google-gdk-license-.+
install:
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"

script:
  - bash ./gradlew :app:assembleDebug

notifications:
  email:
    - xz4214@gmail.com

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
